// Code generated by "stringer -linecomment -output app_gen.go -type=MsgCode"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[Notfound-1]
	_ = x[NotLogin-2]
	_ = x[IsLogined-3]
	_ = x[VIPExpired-4]
	_ = x[NotSetGame-5]
	_ = x[Accelerating-6]
	_ = x[InvalidMonths-7]
	_ = x[GameExist-8]
	_ = x[NotAccelerated-9]
	_ = x[RequireGameId-10]
	_ = x[Unknown-11]
	_ = x[_end-12]
}

const _MsgCode_name = "oknot found没有登录已经登录vip 已过期请先选择加速的游戏游戏已在加速无效月数游戏已存在没有加速请指定游戏未知_end"

var _MsgCode_index = [...]uint8{0, 2, 11, 23, 35, 48, 75, 93, 105, 120, 132, 147, 153, 157}

func (i MsgCode) String() string {
	if i < 0 || i >= MsgCode(len(_MsgCode_index)-1) {
		return "MsgCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MsgCode_name[_MsgCode_index[i]:_MsgCode_index[i+1]]
}
