// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Accelerate(arg1:number):Promise<main.Message[struct {}]>;

export function AddGame(arg1:number):Promise<main.Message[struct {}]>;

export function DisableAccelerate():Promise<main.Message[struct {}]>;

export function GetSelectedGame():Promise<main.Message[main>;

export function GetUser():Promise<main.Message[main>;

export function ListGames():Promise<main.Message[[]main>;

export function Recharge(arg1:number,arg2:string):Promise<main.Message[string]>;

export function RegisterOrLogin(arg1:string,arg2:string):Promise<main.Message[struct {}]>;

export function SearchGame(arg1:string):Promise<main.Message[[]main>;

export function SelectGame(arg1:number):Promise<main.Message[main>;

export function SetGame(arg1:number):Promise<main.Message[struct {}]>;

export function SetGameServer(arg1:number,arg2:string):Promise<main.Message[struct {}]>;

export function SetRouteMode(arg1:number,arg2:boolean):Promise<main.Message[struct {}]>;

export function Stats():Promise<main.Message[main>;
