// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGame(arg1) {
  return window['go']['main']['App']['AddGame'](arg1);
}

export function DelGame(arg1) {
  return window['go']['main']['App']['DelGame'](arg1);
}

export function GetGame(arg1) {
  return window['go']['main']['App']['GetGame'](arg1);
}

export function GetSelectedGame() {
  return window['go']['main']['App']['GetSelectedGame']();
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function ListGames() {
  return window['go']['main']['App']['ListGames']();
}

export function Recharge(arg1, arg2) {
  return window['go']['main']['App']['Recharge'](arg1, arg2);
}

export function RegisterOrLogin(arg1, arg2) {
  return window['go']['main']['App']['RegisterOrLogin'](arg1, arg2);
}

export function SearchGame(arg1) {
  return window['go']['main']['App']['SearchGame'](arg1);
}

export function SelectGame(arg1) {
  return window['go']['main']['App']['SelectGame'](arg1);
}

export function SetGameServer(arg1) {
  return window['go']['main']['App']['SetGameServer'](arg1);
}

export function SetRouteMode(arg1) {
  return window['go']['main']['App']['SetRouteMode'](arg1);
}

export function StartAccele(arg1) {
  return window['go']['main']['App']['StartAccele'](arg1);
}

export function Stats() {
  return window['go']['main']['App']['Stats']();
}

export function StopAccele() {
  return window['go']['main']['App']['StopAccele']();
}
