// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Accelerate(arg1:number):Promise<main.Message>;

export function AddGame(arg1:number):Promise<main.Message>;

export function DisableAccelerate():Promise<main.Message>;

export function GetSelectedGame():Promise<main.GameInfo|main.Message>;

export function GetUser():Promise<main.UserInfo|main.Message>;

export function ListGames():Promise<Array<main.GameInfo>>;

export function Recharge(arg1:number,arg2:string):Promise<string|main.Message>;

export function RegisterOrLogin(arg1:string,arg2:string):Promise<main.Message>;

export function SearchGame(arg1:string):Promise<Array<main.GameInfo>|main.Message>;

export function SelectGame(arg1:number):Promise<main.GameInfo|main.Message>;

export function SetGame(arg1:number):Promise<main.Message>;

export function SetGameServer(arg1:number,arg2:string):Promise<main.Message>;

export function SetRouteMode(arg1:number,arg2:boolean):Promise<main.Message>;

export function Stats():Promise<main.Stats>;
