// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddGame(arg1:number):Promise<main.Message>;

export function DelGame(arg1:number):Promise<main.Message>;

export function GetGame(arg1:number):Promise<main.Message>;

export function GetSelectedGame():Promise<main.Message>;

export function GetUser():Promise<main.Message>;

export function ListGames():Promise<main.Message>;

export function Recharge(arg1:number,arg2:string):Promise<main.Message>;

export function RegisterOrLogin(arg1:string,arg2:string):Promise<main.Message>;

export function SearchGame(arg1:string):Promise<main.Message>;

export function SelectGame(arg1:number):Promise<main.Message>;

export function SetGameServer(arg1:string):Promise<main.Message>;

export function SetRouteMode(arg1:boolean):Promise<main.Message>;

export function StartAccele(arg1:number):Promise<main.Message>;

export function Stats():Promise<main.Stats>;

export function StopAccele():Promise<main.Message>;
